version: 2
jobs:
  build:
    docker:
      - image: cimg/base:stable
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker
      - run:
          working_directory: delta-renderer-base
          command: ./build.sh
